osx_image: xcode8.2
language: objective-c
podfile: ./Tests/Podfile

before_install:
  # Fix Travis  xcodebuild exited with 65 https://github.com/travis-ci/travis-ci/issues/6675#issuecomment-257964767
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep -m 1 "iPhone 6 (10.2" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID
  - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID

script:
  - set -o pipefail
  - travis_retry xcodebuild -workspace ./Tests/Example.xcworkspace -scheme Example -sdk iphonesimulator -destination "id=$IOS_SIMULATOR_UDID" test | xcpretty -c